apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: capital-resources-db
  name: capital-resources-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
