apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
