apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        service: {{ .Values.serviceName }}
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: capital-resources
            - name: POSTGRES_PASSWORD
              value: 6jcl2#gbnkj14367dwe&5
            - name: POSTGRES_USER
              value: admin
          image: postgis/postgis:12-3.0
          name: {{ .Values.serviceName }}
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "1024M"
              cpu: "200m"
            limits:
              cpu: "2"
              memory: 2024M
      volumes:
        - name: {{ .Values.serviceName }}
          persistentVolumeClaim:
            claimName: {{ .Values.serviceName }}