apiVersion: v1
kind: PersistentVolume
metadata:
  name: store-capital-db-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data
