apiVersion: v1
kind: Service
metadata:
  labels:
    service: auth
  name: auth
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: auth
status:
  loadBalancer: {}
