apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      service: auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: auth
    spec:
      containers:
        - env:
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KEYCLOAK_USER
              value: admin
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          image: jboss/keycloak:latest
          name: auth
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/jboss/keycloak/standalone/data/
              name: auth-claim0
      volumes:
        - name: auth-claim0
          persistentVolumeClaim:
            claimName: auth-claim0
status: {}
