version: '3'

services:
  redis:
    image: redis:5.0
    ports:
      - 6379

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 5672
      - 15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: cg@i7!dci99087fvtt
  
  infra:
    image: infra
    ports:
      - 80
    depends_on:
      - capital-resources
    environment:
      WEB_REALM: master
      WEB_AUTH_URL: /auth
      WEB_CLIENT_ID: infra-frontend

  capital-resources:
    image: docker.nntc.pro/capital-resources:dev
    ports:
      - 80
    depends_on:
      - capital-resources-db
      - redis
      - rabbitmq
      - auth
    environment:
      KEYCLOAK__ADDRESS: http://auth/auth/realms/master
      CONNECTIONSTRINGS__DATABASE: Host=capital-resources-db;Database=capital-resources;Username=admin;Password=6jcl2#gbnkj14367dwe&5
      CONNECTIONSTRINGS__RABBITMQ: host=rabbitmq:5672;username=rabbit;password=cg@i7!dci99087fvtt
      CONNECTIONSTRINGS__REDIS: redis:6379

  capital-resources-db:
    image: postgis/postgis:12-3.0
    ports:
      - 5432
    environment:
      POSTGRES_DB: capital-resources
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 6jcl2#gbnkj14367dwe&5

  auth:
    image: jboss/keycloak:latest
    ports:
      - 8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - .local/keycloak/:/opt/jboss/keycloak/standalone/data/