apiVersion: batch/v1
kind: Job
metadata:
  name: infrastructure-auth-client
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: infrastructure-auth-client
    spec:
      containers:
      - name: infrastructure-auth-client
        image: curlimages/curl
        command:
        - /bin/sh
        - -c
        - |
          RESULT=`curl --data "username=admin&password=admin&grant_type=password&client_id=admin-cli" http://auth/auth/realms/master/protocol/openid-connect/token
          TOKEN=`echo $RESULT | sed 's/.*access_token":"//g' | sed 's/".*//g'`
          curl -X POST -d '{ "clientId": "infrastructure" }' -H "Content-Type:application/json" -H "Authorization: bearer ${TOKEN}" http://auth/auth/realms/master/clients-registrations/default
      restartPolicy: Never