apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIubm50Yy5wcm8iOnsidXNlcm5hbWUiOiJubnRjX3VzZXIiLCJwYXNzd29yZCI6IntoZnlia2JvdFlZTlciLCJhdXRoIjoiYm01MFkxOTFjMlZ5T250b1pubGlhMkp2ZEZsWlRsYz0ifX19
kind: Secret
metadata:
  creationTimestamp: "2021-11-29T12:56:20Z"
  name: regcred
  namespace: default
  resourceVersion: "19793"
  uid: 0c27d17b-56bb-487d-b7fb-33739707e9a1
type: kubernetes.io/dockerconfigjson