apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: auth-claim0
  name: {{ .Values.serviceName }}-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
