apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: {{ .Values.serviceName }}
status:
  loadBalancer: {}
