apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Values.serviceName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: {{ .Values.serviceName }}
    spec:
      containers:
        - env:
            - name: KEYCLOAK_PASSWORD
              value: {{ .Values.password }}
            - name: KEYCLOAK_USER
              value: admin
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          image: {{ .Values.imageName }}
          name: {{ .Values.serviceName }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/jboss/keycloak/standalone/data/
              name: {{ .Values.serviceName }}-claim0
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              cpu: "2"
              memory: 2024M
      volumes:
        - name: {{ .Values.serviceName }}-claim0
          persistentVolumeClaim:
            claimName: {{ .Values.serviceName }}-claim0
status: {}
