apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  storageClassName: "slow"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2500Mi
status: {}
