apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress-sert
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /auth-sert
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.serviceName }}
                port:
                  number: 8080
  tls: 
    - 
      hosts: 
        - {{ .Values.host }}
      secretName: main-secret
  ingressClassName: nginx
