apiVersion: v1
kind: PersistentVolume
metadata:
  name: store2
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data2
