apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.serviceName }}-db
  name: {{ .Values.serviceName }}-db
spec:
  ports:
    - name: "5432"
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    service: {{ .Values.serviceName }}-db
