apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  ports:
    - name: "3000"
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    service: {{ .Values.serviceName }}
