apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service: {{ .Values.serviceName }}
status:
  loadBalancer: {}
