apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq
  strategy: {}
  template:
    metadata:
      labels:
        service: rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: cg@i7!dci99087fvtt
            - name: RABBITMQ_DEFAULT_USER
              value: rabbit
          image: {{ .Values.imageName }}
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              cpu: "1"
              memory: 1024M
status: {}
